Repository Axel77g/TP-GIT-Groupe-5, pull requests merged in 2023-03, with the labels that each got.

#10 Feature/sync GitHub and gitlab
  .hook/pre-commit
  src/main.js
  syncRepo.sh
  yarn.lock
Labels: enhancement

#14 Merge develop into main to get new documentation update
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation

#15 Feature/contributing enhancement
  CONTRIBUTING.md
Labels: documentation

#11 [Debug] Add vite-plugin-checker
  package-lock.json
  package.json
  vite.config.js
  yarn.lock
Labels: enhancement

#16 Release/v1.0.0
  .hook/pre-commit
  CONTRIBUTING.md
  index.html
  package-lock.json
  package.json
  public/robot.txt
  src/index.html
  src/main.js
  syncRepo.sh
  vite.config.js
  yarn.lock
Labels: bug, documentation, enhancement

#17 [HOOK] add pre-push esling sh scrip
  .hook/pre-push
Labels: bug
